site:
  server:
    # each line is a partition (Paxos group), the first is the master site_name:port
    # the last column is the learner
    - ["s101:8001", "s201:8101", "s301:8201", "s401:8301"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  s201: p1
  s202: p1
  s203: p1
  s301: p2
  s302: p2
  s303: p2
  s401: learner 
  s402: learner
  s403: learner

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
  learner: 127.0.0.1