# yaml-cpp online: https://yaml-online-parser.appspot.com/
# suppose m shards and n warehouse each shard; 
# the first replica to be the leader by default
# https://aju9mlkupe.feishu.cn/docs/doccnG7AZ1gjFmo9CcgRMidJO5f Port allocation policy

shards: 7  # number of shards
replicas: 3  # number of replicas
warehouses: 22  # number of warehouses per shard, keep same as the tpcc worker threads
localhost:
  - name: shard0
    index: 0
    ip:   127.0.0.1
    port: 31000
  - name: shard1
    index: 1
    ip:   127.0.0.1
    port: 31100
  - name: shard2
    index: 2
    ip:   127.0.0.1
    port: 31200
  - name: shard3
    index: 3
    ip:   127.0.0.1
    port: 31300
  - name: shard4
    index: 4
    ip:   127.0.0.1
    port: 31400
  - name: shard5
    index: 5
    ip:   127.0.0.1
    port: 31500
  - name: shard6
    index: 6
    ip:   127.0.0.1
    port: 31600
p1:
  - name: shard0
    index: 0
    ip:  127.0.0.1
    port: 32000
  - name: shard1
    index: 1
    ip: 127.0.0.1
    port: 32100
  - name: shard2
    index: 2
    ip:  127.0.0.1
    port: 32200
  - name: shard3
    index: 3
    ip:  127.0.0.1
    port: 32300
  - name: shard4
    index: 4
    ip:  127.0.0.1
    port: 32400
  - name: shard5
    index: 5
    ip:  127.0.0.1
    port: 32500
  - name: shard6
    index: 6
    ip:  127.0.0.1
    port: 32600
p2:
  - name: shard0
    index: 0
    ip:  127.0.0.1
    port: 33000
  - name: shard1
    index: 1
    ip:  127.0.0.1
    port: 33100
  - name: shard2
    index: 2
    ip:  127.0.0.1
    port: 33200
  - name: shard3
    index: 3
    ip:  127.0.0.1
    port: 33300
  - name: shard4
    index: 4
    ip:  127.0.0.1
    port: 33400
  - name: shard5
    index: 5
    ip:  127.0.0.1
    port: 33500
  - name: shard6
    index: 6
    ip:  127.0.0.1
    port: 33600
learner:
 - name: shard0
   index: 0
   ip:  127.0.0.1
   port: 34000
 - name: shard1
   index: 1
   ip:  127.0.0.1
   port: 34100
 - name: shard2
   index: 2
   ip:  127.0.0.1
   port: 34200
 - name: shard3
   index: 3
   ip:  127.0.0.1
   port: 34300
 - name: shard4
   index: 4
   ip:  127.0.0.1
   port: 34400
 - name: shard5
   index: 5
   ip:  127.0.0.1
   port: 34500
 - name: shard6
   index: 6
   ip:  127.0.0.1
   port: 34600
memlocalhost: 6001 # mem control port
memlearner: 6001
memp1: 6002
memp2: 6003
