# CMake generated Testfile for 
# Source directory: /home/users/zyang2/mako
# Build directory: /home/users/zyang2/mako
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_marshal "/home/users/zyang2/mako/test_marshal")
set_tests_properties(test_marshal PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1137;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_rpc "/home/users/zyang2/mako/test_rpc")
set_tests_properties(test_rpc PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1144;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_future "/home/users/zyang2/mako/test_future")
set_tests_properties(test_future PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1158;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_masstree "/home/users/zyang2/mako/test_masstree")
set_tests_properties(test_masstree PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1171;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_masstree_internals "/home/users/zyang2/mako/test_masstree_internals")
set_tests_properties(test_masstree_internals PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1178;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_masstree_multi_instance "/home/users/zyang2/mako/test_masstree_multi_instance")
set_tests_properties(test_masstree_multi_instance PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1185;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_silo_runtime "/home/users/zyang2/mako/test_silo_runtime")
set_tests_properties(test_silo_runtime PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1192;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_silo_multi_site_stress "/home/users/zyang2/mako/test_silo_multi_site_stress")
set_tests_properties(test_silo_multi_site_stress PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1199;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_reactor "/home/users/zyang2/mako/test_reactor")
set_tests_properties(test_reactor PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1221;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_coroutine "/home/users/zyang2/mako/test_coroutine")
set_tests_properties(test_coroutine PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1229;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_rpc_extended "/home/users/zyang2/mako/test_rpc_extended")
set_tests_properties(test_rpc_extended PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1237;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_reactor_extended "/home/users/zyang2/mako/test_reactor_extended")
set_tests_properties(test_reactor_extended PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1244;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_arc_mutex_thread "/home/users/zyang2/mako/test_arc_mutex_thread")
set_tests_properties(test_arc_mutex_thread PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1251;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_timeout_race "/home/users/zyang2/mako/test_timeout_race")
set_tests_properties(test_timeout_race PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1258;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_and_event "/home/users/zyang2/mako/test_and_event")
set_tests_properties(test_and_event PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1265;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_transport_backend "/home/users/zyang2/mako/test_transport_backend")
set_tests_properties(test_transport_backend PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1273;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(stress_transport_backend "/home/users/zyang2/mako/stress_transport_backend")
set_tests_properties(stress_transport_backend PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1281;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_transport_integration "/home/users/zyang2/mako/test_transport_integration")
set_tests_properties(test_transport_integration PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1299;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(test_erpc_integration "/home/users/zyang2/mako/test_erpc_integration")
set_tests_properties(test_erpc_integration PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1318;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(simpleTransaction "/home/users/zyang2/mako/simpleTransaction")
set_tests_properties(simpleTransaction PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1322;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(rpcbench "bash" "-c" "pkill -9 rpcbench || true; ./build/rpcbench -s 127.0.0.1:8848 > /dev/null 2>&1 & SERVER_PID=\$!; sleep 1; ./build/rpcbench -c 127.0.0.1:8848 -n 3 -t 4 -o 100; RESULT=\$?; kill \$SERVER_PID 2>/dev/null || true; exit \$RESULT")
set_tests_properties(rpcbench PROPERTIES  TIMEOUT "30" WORKING_DIRECTORY "/home/users/zyang2/mako" _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1325;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(SiloVarintTests "/home/users/zyang2/mako/test_silo_varint")
set_tests_properties(SiloVarintTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1398;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(SiloRCUThreadTests "/home/users/zyang2/mako/test_silo_rcu_thread")
set_tests_properties(SiloRCUThreadTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1421;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(SiloAllocatorTupleTests "/home/users/zyang2/mako/test_silo_allocator_tuple")
set_tests_properties(SiloAllocatorTupleTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1444;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(STOTransactionTests "/home/users/zyang2/mako/test_sto_transaction")
set_tests_properties(STOTransactionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1467;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
add_test(STOTransactionRealTests "/home/users/zyang2/mako/test_sto_transaction_real")
set_tests_properties(STOTransactionRealTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/zyang2/mako/CMakeLists.txt;1490;add_test;/home/users/zyang2/mako/CMakeLists.txt;0;")
subdirs("third-party/erpc")
