# CMake generated Testfile for 
# Source directory: /home/users/ssoumojit/mako
# Build directory: /home/users/ssoumojit/mako/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_marshal "/home/users/ssoumojit/mako/build_debug/test_marshal")
set_tests_properties(test_marshal PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1260;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_client_service "/home/users/ssoumojit/mako/build_debug/test_client_service")
set_tests_properties(test_client_service PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1267;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_config_schema "/home/users/ssoumojit/mako/build_debug/test_config_schema")
set_tests_properties(test_config_schema PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1274;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_sharding_policy "/home/users/ssoumojit/mako/build_debug/test_sharding_policy")
set_tests_properties(test_sharding_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1281;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_sharding_policy_cache "/home/users/ssoumojit/mako/build_debug/test_sharding_policy_cache")
set_tests_properties(test_sharding_policy_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1288;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_shard_router "/home/users/ssoumojit/mako/build_debug/test_shard_router")
set_tests_properties(test_shard_router PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1295;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_tpcc_sharding "/home/users/ssoumojit/mako/build_debug/test_tpcc_sharding")
set_tests_properties(test_tpcc_sharding PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1302;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_fiber "/home/users/ssoumojit/mako/build_debug/test_fiber")
set_tests_properties(test_fiber PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1309;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_config_store "/home/users/ssoumojit/mako/build_debug/test_config_store")
set_tests_properties(test_config_store PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1316;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_config_service "/home/users/ssoumojit/mako/build_debug/test_config_service")
set_tests_properties(test_config_service PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1324;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_config_client "/home/users/ssoumojit/mako/build_debug/test_config_client")
set_tests_properties(test_config_client PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1332;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_config_failure "/home/users/ssoumojit/mako/build_debug/test_config_failure")
set_tests_properties(test_config_failure PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1339;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_sharding_startup "/home/users/ssoumojit/mako/build_debug/test_sharding_startup")
set_tests_properties(test_sharding_startup PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1346;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc "/home/users/ssoumojit/mako/build_debug/test_rpc")
set_tests_properties(test_rpc PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1353;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_load_balancer "/home/users/ssoumojit/mako/build_debug/test_load_balancer")
set_tests_properties(test_load_balancer PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1360;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_idempotency "/home/users/ssoumojit/mako/build_debug/test_idempotency")
set_tests_properties(test_idempotency PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1367;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_completion_tracker "/home/users/ssoumojit/mako/build_debug/test_completion_tracker")
set_tests_properties(test_completion_tracker PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1374;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(rpc_chaos_test "/home/users/ssoumojit/mako/build_debug/rpc_chaos_test")
set_tests_properties(rpc_chaos_test PROPERTIES  LABELS "chaos" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1381;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_future "/home/users/ssoumojit/mako/build_debug/test_future")
set_tests_properties(test_future PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1396;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_masstree "/home/users/ssoumojit/mako/build_debug/test_masstree")
set_tests_properties(test_masstree PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1409;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_masstree_internals "/home/users/ssoumojit/mako/build_debug/test_masstree_internals")
set_tests_properties(test_masstree_internals PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1416;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_masstree_multi_instance "/home/users/ssoumojit/mako/build_debug/test_masstree_multi_instance")
set_tests_properties(test_masstree_multi_instance PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1423;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_silo_runtime "/home/users/ssoumojit/mako/build_debug/test_silo_runtime")
set_tests_properties(test_silo_runtime PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1430;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_silo_multi_site_stress "/home/users/ssoumojit/mako/build_debug/test_silo_multi_site_stress")
set_tests_properties(test_silo_multi_site_stress PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1437;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_reactor "/home/users/ssoumojit/mako/build_debug/test_reactor")
set_tests_properties(test_reactor PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1459;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_coroutine "/home/users/ssoumojit/mako/build_debug/test_coroutine")
set_tests_properties(test_coroutine PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1467;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_extended "/home/users/ssoumojit/mako/build_debug/test_rpc_extended")
set_tests_properties(test_rpc_extended PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1475;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_reactor_extended "/home/users/ssoumojit/mako/build_debug/test_reactor_extended")
set_tests_properties(test_reactor_extended PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1482;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_arc_mutex_thread "/home/users/ssoumojit/mako/build_debug/test_arc_mutex_thread")
set_tests_properties(test_arc_mutex_thread PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1489;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_timeout_race "/home/users/ssoumojit/mako/build_debug/test_timeout_race")
set_tests_properties(test_timeout_race PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1496;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_and_event "/home/users/ssoumojit/mako/build_debug/test_and_event")
set_tests_properties(test_and_event PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1503;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_transport_backend "/home/users/ssoumojit/mako/build_debug/test_transport_backend")
set_tests_properties(test_transport_backend PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1511;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(stress_transport_backend "/home/users/ssoumojit/mako/build_debug/stress_transport_backend")
set_tests_properties(stress_transport_backend PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1519;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_transport_integration "/home/users/ssoumojit/mako/build_debug/test_transport_integration")
set_tests_properties(test_transport_integration PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1537;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_erpc_integration "/home/users/ssoumojit/mako/build_debug/test_erpc_integration")
set_tests_properties(test_erpc_integration PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1556;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_connection_state "/home/users/ssoumojit/mako/build_debug/test_rpc_connection_state")
set_tests_properties(test_rpc_connection_state PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1568;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_reconnect_policy "/home/users/ssoumojit/mako/build_debug/test_rpc_reconnect_policy")
set_tests_properties(test_rpc_reconnect_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1575;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_circuit_breaker "/home/users/ssoumojit/mako/build_debug/test_rpc_circuit_breaker")
set_tests_properties(test_rpc_circuit_breaker PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1582;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_heartbeat "/home/users/ssoumojit/mako/build_debug/test_rpc_heartbeat")
set_tests_properties(test_rpc_heartbeat PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1589;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_errors "/home/users/ssoumojit/mako/build_debug/test_rpc_errors")
set_tests_properties(test_rpc_errors PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1596;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_callbacks "/home/users/ssoumojit/mako/build_debug/test_rpc_callbacks")
set_tests_properties(test_rpc_callbacks PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1603;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_request_queue "/home/users/ssoumojit/mako/build_debug/test_rpc_request_queue")
set_tests_properties(test_rpc_request_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1610;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_request_buffering "/home/users/ssoumojit/mako/build_debug/test_rpc_request_buffering")
set_tests_properties(test_rpc_request_buffering PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1616;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_timeout_retry "/home/users/ssoumojit/mako/build_debug/test_rpc_timeout_retry")
set_tests_properties(test_rpc_timeout_retry PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1623;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_state_integration "/home/users/ssoumojit/mako/build_debug/test_rpc_state_integration")
set_tests_properties(test_rpc_state_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1634;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_reconnect_integration "/home/users/ssoumojit/mako/build_debug/test_rpc_reconnect_integration")
set_tests_properties(test_rpc_reconnect_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1641;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_circuit_breaker_integration "/home/users/ssoumojit/mako/build_debug/test_rpc_circuit_breaker_integration")
set_tests_properties(test_rpc_circuit_breaker_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1648;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_error_integration "/home/users/ssoumojit/mako/build_debug/test_rpc_error_integration")
set_tests_properties(test_rpc_error_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1655;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_combined_reliability "/home/users/ssoumojit/mako/build_debug/test_rpc_combined_reliability")
set_tests_properties(test_rpc_combined_reliability PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1662;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_graceful_shutdown "/home/users/ssoumojit/mako/build_debug/test_rpc_graceful_shutdown")
set_tests_properties(test_rpc_graceful_shutdown PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1669;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_restart_detection "/home/users/ssoumojit/mako/build_debug/test_rpc_restart_detection")
set_tests_properties(test_rpc_restart_detection PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1676;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_validation "/home/users/ssoumojit/mako/build_debug/test_rpc_validation")
set_tests_properties(test_rpc_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1683;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_metrics "/home/users/ssoumojit/mako/build_debug/test_rpc_metrics")
set_tests_properties(test_rpc_metrics PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1690;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_client_pool "/home/users/ssoumojit/mako/build_debug/test_rpc_client_pool")
set_tests_properties(test_rpc_client_pool PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1697;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_log_storage "/home/users/ssoumojit/mako/build_debug/test_rpc_log_storage")
set_tests_properties(test_rpc_log_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1704;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_rocksdb_log_storage "/home/users/ssoumojit/mako/build_debug/test_rpc_rocksdb_log_storage")
set_tests_properties(test_rpc_rocksdb_log_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1711;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_txn_timeout "/home/users/ssoumojit/mako/build_debug/test_txn_timeout")
set_tests_properties(test_txn_timeout PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1718;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_stress_crash "/home/users/ssoumojit/mako/build_debug/test_rpc_stress_crash")
set_tests_properties(test_rpc_stress_crash PROPERTIES  LABELS "stress" TIMEOUT "1800" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1728;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(test_rpc_partition "/home/users/ssoumojit/mako/build_debug/test_rpc_partition")
set_tests_properties(test_rpc_partition PROPERTIES  LABELS "stress" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1739;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(simpleTransaction "/home/users/ssoumojit/mako/build_debug/simpleTransaction")
set_tests_properties(simpleTransaction PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1746;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(rpcbench "bash" "-c" "pkill -9 rpcbench || true; ./build/rpcbench -s 127.0.0.1:8848 > /dev/null 2>&1 & SERVER_PID=\$!; sleep 1; ./build/rpcbench -c 127.0.0.1:8848 -n 3 -t 4 -o 100; RESULT=\$?; kill \$SERVER_PID 2>/dev/null || true; exit \$RESULT")
set_tests_properties(rpcbench PROPERTIES  TIMEOUT "30" WORKING_DIRECTORY "/home/users/ssoumojit/mako" _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1749;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(SiloVarintTests "/home/users/ssoumojit/mako/build_debug/test_silo_varint")
set_tests_properties(SiloVarintTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1826;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(SiloRCUThreadTests "/home/users/ssoumojit/mako/build_debug/test_silo_rcu_thread")
set_tests_properties(SiloRCUThreadTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1849;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(SiloAllocatorTupleTests "/home/users/ssoumojit/mako/build_debug/test_silo_allocator_tuple")
set_tests_properties(SiloAllocatorTupleTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1872;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(STOTransactionTests "/home/users/ssoumojit/mako/build_debug/test_sto_transaction")
set_tests_properties(STOTransactionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1895;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
add_test(STOTransactionRealTests "/home/users/ssoumojit/mako/build_debug/test_sto_transaction_real")
set_tests_properties(STOTransactionRealTests PROPERTIES  _BACKTRACE_TRIPLES "/home/users/ssoumojit/mako/CMakeLists.txt;1918;add_test;/home/users/ssoumojit/mako/CMakeLists.txt;0;")
subdirs("third-party/erpc")
