version = 1

[modules."rusty::sys::time"]
cpp_module = "rusty"
namespace = "rusty::sys::time"

[modules."rusty::sys::time".symbols.clock_monotonic_us]
kind = "function"
callable_signatures = ["uint64_t()"]

[modules."rusty::sys::time".symbols.clock_realtime_coarse_us]
kind = "function"
callable_signatures = ["uint64_t()"]

[modules."rusty::sys::time".symbols.gettimeofday_us]
kind = "function"
callable_signatures = ["uint64_t()"]

[modules."rusty::sys::time".symbols.sleep_us]
kind = "function"
callable_signatures = ["void(uint64_t)"]
