version = 1

[modules.std]
cpp_module = "std"
namespace = "std"

[modules.std.symbols.string]
kind = "type"
callable_signatures = []

[modules.std.symbols.strtoul]
kind = "function"
callable_signatures = ["unsigned long(const char*,char**,int)"]

[modules."rusty::sys"]
cpp_module = "rusty"
namespace = "rusty::sys"

[modules."rusty::sys".symbols."process::getpid"]
kind = "function"
callable_signatures = ["int()"]

[modules."rusty::sys".symbols."process::sysconf"]
kind = "function"
callable_signatures = ["long(int)"]

[modules."rusty::sys".symbols."process::process_times"]
kind = "function"
callable_signatures = ["ProcessTimes()"]

[modules."rusty::sys".symbols."process::sysinfo"]
kind = "function"
callable_signatures = ["SysInfo()"]

[modules."rusty::sys".symbols."fs::read_to_string"]
kind = "function"
callable_signatures = ["Result<std::string,io::Error>(std::string_view)"]
