version = 1

[modules."rrr::reactor"]
cpp_module = "rrr.reactor"
namespace = "rrr"

[modules."rrr::reactor".symbols.Fiber]
kind = "type"
callable_signatures = []

[modules."rrr::reactor".symbols."Fiber::current_fiber"]
kind = "method"
callable_signatures = ["rusty::Option<rusty::Rc<Fiber>>()"]

[modules."rrr::reactor".symbols."Fiber::yield_"]
kind = "method"
callable_signatures = ["void()"]

[modules."rrr::reactor".symbols.fiber_sleep]
kind = "function"
callable_signatures = ["void(uint64_t)"]
