version = 1

[modules."rrr::serializable"]
cpp_module = "rrr.serializable"
namespace = "rrr"

[modules."rrr::serializable".symbols.BinaryWriteArchive]
kind = "type"
callable_signatures = []

[modules."rrr::serializable".symbols.BinaryReadArchive]
kind = "type"
callable_signatures = []

[modules."rrr::serializable".symbols."Serialize_::serialize"]
kind = "function_template"
callable_signatures = ["void(const uint64_t&,BinaryWriteArchive&)"]

[modules."rrr::serializable".symbols."Deserialize_::deserialize"]
kind = "function_template"
callable_signatures = ["void(uint64_t&,BinaryReadArchive&)"]
