version = 1

[modules."rrr::debugging"]
cpp_module = "rrr.debugging"
namespace = "rrr"

[modules."rrr::debugging".symbols.verify]
kind = "function"
callable_signatures = ["void(const bool&)"]

[modules.std]
cpp_module = "std"
namespace = "std"

[modules.std.symbols.string]
kind = "type"
callable_signatures = []

[modules.std.symbols.cout]
kind = "object"
callable_signatures = []
