version = 1

[modules.std]
cpp_module = "std"
namespace = "std"

[modules.std.symbols.string]
kind = "type"
callable_signatures = []

[modules.std.symbols.vector]
kind = "type_template"
callable_signatures = []
