version = 1

[modules."rrr::debugging"]
cpp_module = "rrr.debugging"
namespace = "rrr"

[modules."rrr::debugging".symbols.verify]
kind = "function_template"
callable_signatures = ["void(const bool&)"]

[modules."rusty::sys::time"]
cpp_module = "rusty"
namespace = "rusty::sys::time"

[modules."rusty::sys::time".symbols.sleep_us]
kind = "function"
callable_signatures = ["void(uint64_t)"]
