//! Golden-corpus contract test: the crate's encoders must produce the
//! exact bytes the C++ implementation produces.
//!
//! The corpus (tests/golden/wire_corpus.txt) is GENERATED by the C++
//! side (`src/rrr/tests/wire_golden_test.cc` with SRPC_GOLDEN_WRITE=1)
//! and asserted by BOTH sides. Keep the case list here in lockstep
//! with that file — this test fails on unknown or missing names.

use srpc::wire::{Serialize, WriteArchive, V32, V64};

fn hex(bytes: &[u8]) -> String {
    if bytes.is_empty() {
        return String::from("-");
    }
    let mut out = String::new();
    let mut i = 0;
    while i < bytes.len() {
        out.push_str(&format!("{:02x}", bytes[i]));
        i += 1;
    }
    out
}

fn encode_case<F: FnOnce(&mut WriteArchive)>(fill: F) -> String {
    let mut ar = WriteArchive::new();
    fill(&mut ar);
    hex(ar.as_bytes())
}

/// Build the full named case list — mirrors build_corpus() in
/// wire_golden_test.cc exactly.
fn build_corpus() -> Vec<(String, String)> {
    let mut cs: Vec<(String, String)> = Vec::new();

    // --- v32 boundaries ---------------------------------------------------
    let v32_vals: [i32; 21] = [
        0,
        1,
        -1,
        63,
        64,
        -64,
        -65,
        8191,
        8192,
        -8192,
        -8193,
        1048575,
        1048576,
        -1048576,
        -1048577,
        134217727,
        134217728,
        -134217728,
        -134217729,
        2147483647,
        -2147483648,
    ];
    let mut i = 0;
    while i < v32_vals.len() {
        let v = v32_vals[i];
        cs.push((format!("v32_{}", i), encode_case(|ar| V32(v).serialize(ar))));
        i += 1;
    }

    // --- v64 boundaries (incl. the 8-length quirk cases) -------------------
    let v64_vals: [i64; 21] = [
        0,
        1,
        -1,
        63,
        -64,
        8191,
        -8192,
        1048575,
        -1048576,
        134217727,
        -134217728,
        17179869183,
        -17179869184,
        2199023255551,
        -2199023255552,
        281474976710655,
        -281474976710656,
        36028797018963967,  // val_size 8: quirk
        -36028797018963968, // val_size 8: quirk
        9223372036854775807,
        -9223372036854775808,
    ];
    let mut i = 0;
    while i < v64_vals.len() {
        let v = v64_vals[i];
        cs.push((format!("v64_{}", i), encode_case(|ar| V64(v).serialize(ar))));
        i += 1;
    }

    // --- fixed-width scalars ----------------------------------------------
    cs.push((
        String::from("i8_min"),
        encode_case(|ar| (-128i8).serialize(ar)),
    ));
    cs.push((
        String::from("i16_min"),
        encode_case(|ar| (-32768i16).serialize(ar)),
    ));
    cs.push((
        String::from("i32_pattern"),
        encode_case(|ar| 0x01020304i32.serialize(ar)),
    ));
    cs.push((
        String::from("i64_pattern"),
        encode_case(|ar| 0x0102030405060708i64.serialize(ar)),
    ));
    cs.push((
        String::from("u8_max"),
        encode_case(|ar| 255u8.serialize(ar)),
    ));
    cs.push((
        String::from("u16_max"),
        encode_case(|ar| 65535u16.serialize(ar)),
    ));
    cs.push((
        String::from("u32_max"),
        encode_case(|ar| 4294967295u32.serialize(ar)),
    ));
    cs.push((
        String::from("u64_max"),
        encode_case(|ar| 18446744073709551615u64.serialize(ar)),
    ));
    // Not f64::consts::PI: must match the C++ generator's `3.14159`
    // literal byte-for-byte.
    #[allow(clippy::approx_constant)]
    cs.push((
        String::from("f64_pi"),
        encode_case(|ar| 3.14159f64.serialize(ar)),
    ));

    // --- strings ----------------------------------------------------------
    cs.push((
        String::from("str_empty"),
        encode_case(|ar| "".serialize(ar)),
    ));
    cs.push((String::from("str_a"), encode_case(|ar| "a".serialize(ar))));
    cs.push((
        String::from("str_hello"),
        encode_case(|ar| "hello rrr wire".serialize(ar)),
    ));
    cs.push((
        String::from("str_200"),
        encode_case(|ar| "x".repeat(200).serialize(ar)),
    ));

    // --- containers -------------------------------------------------------
    cs.push((
        String::from("vec_i32_empty"),
        encode_case(|ar| Vec::<i32>::new().serialize(ar)),
    ));
    cs.push((
        String::from("vec_i32_123"),
        encode_case(|ar| vec![1i32, -2, 3].serialize(ar)),
    ));
    cs.push((
        String::from("vec_str"),
        encode_case(|ar| vec![String::from("x"), String::from("yz")].serialize(ar)),
    ));
    cs.push((
        String::from("pair_v64_str"),
        encode_case(|ar| (V64(7), String::from("kv")).serialize(ar)),
    ));

    // --- request-body composite: [v64 xid][i32 rpc_id][string arg] --------
    cs.push((
        String::from("request_body"),
        encode_case(|ar| {
            V64(1).serialize(ar);
            0x1234i32.serialize(ar);
            "payload".serialize(ar);
        }),
    ));

    // --- ordered map: [v64 len][k,v...] in key order -----------------------
    cs.push((
        String::from("map_i32_str"),
        encode_case(|ar| {
            let mut m: std::collections::BTreeMap<i32, String> = std::collections::BTreeMap::new();
            m.insert(7, String::from("seven"));
            m.insert(-1, String::from("neg"));
            m.serialize(ar);
        }),
    ));

    // --- frame codec: [i32 LE (size | ext<<31)][payload] -------------------
    {
        let frame_hex = |payload: &[u8], ext: bool| -> String {
            let mut out: Vec<u8> = Vec::new();
            assert!(srpc::wire::frame::encode_into(&mut out, payload, ext));
            hex(&out)
        };
        cs.push((String::from("frame_empty"), frame_hex(b"", false)));
        cs.push((String::from("frame_hello"), frame_hex(b"hello", false)));
        cs.push((String::from("frame_ext_x"), frame_hex(b"x", true)));
    }

    cs
}

#[test]
fn corpus_matches_rust() {
    let corpus = include_str!("golden/wire_corpus.txt");
    let mut want: Vec<(String, String)> = Vec::new();
    for line in corpus.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.splitn(2, ' ');
        let name = parts.next().expect("name");
        let hex = parts.next().expect("hex");
        want.push((String::from(name), String::from(hex)));
    }

    let got = build_corpus();
    assert_eq!(
        want.len(),
        got.len(),
        "corpus/case-list drift — regenerate the corpus (C++ side, \
         SRPC_GOLDEN_WRITE=1) and sync this file"
    );
    let mut i = 0;
    while i < got.len() {
        let (name, g) = &got[i];
        let mut found = false;
        let mut j = 0;
        while j < want.len() {
            if &want[j].0 == name {
                assert_eq!(&want[j].1, g, "byte mismatch for {}", name);
                found = true;
                break;
            }
            j += 1;
        }
        assert!(found, "missing corpus entry: {}", name);
        i += 1;
    }
}
