#!/usr/bin/env python3
"""Generate docs/migration/raft/cpp-rust-correspondence.md from the tree.

WHY GENERATED. Every number in that document rotted within a day of being
typed: server_h.rs drifted 5009 -> 5017, transport.rs 460 -> 647, the kernel
count was wrong three different ways depending on how you counted, and the
"26 out-params" was a grep line-count rather than a count of out-parameters.
A figure a reader cannot refute is worse than no figure, so they are computed
here, with the counting rule stated beside each one.

  python3 scripts/gen_correspondence.py            rewrite the document
  python3 scripts/gen_correspondence.py --check    fail if it is stale
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / "docs/migration/raft/cpp-rust-correspondence.md"
RS = sorted((ROOT / "src/deptran/raft/src").glob("*.rs"))


def lines(rel):
    p = ROOT / rel
    return len(p.read_text(errors="replace").split("\n")) - 1 if p.is_file() else 0


def kernels():
    """Distinct raft_* names declared in `extern "C"` blocks under raft/src.

    The union across files, de-duplicated: five names are declared in two
    modules each, and counting per-file double-counts them."""
    names = set()
    for f in RS:
        for block in re.finditer(r'unsafe extern "C" \{(.*?)\n\}', f.read_text(), re.S):
            names |= set(re.findall(r"\bfn (raft_\w+)", block.group(1)))
    return len(names)


def exports(header):
    """Prototypes in a C ABI header -- one per non-comment line ending in ');'."""
    text = (ROOT / header).read_text()
    return len([l for l in text.split("\n")
                if l.rstrip().endswith(");") and not l.lstrip().startswith("//")])


def catch_sites():
    """raft_catch CALL sites. grep counts the template definition too."""
    text = (ROOT / "src/deptran/raft/server.cc").read_text()
    return len(re.findall(r"raft_catch\(", text)) - len(
        re.findall(r"^\w[\w:<>,\s&*]*\braft_catch\(", text, re.M))


def out_params():
    """Methods with a `self` receiver AND a scalar out-pointer parameter."""
    n = 0
    for f in RS + [ROOT / "src/deptran/raft/src/scheduler_h.rs"]:
        if not f.is_file():
            continue
        for m in re.finditer(r"\bfn \w+\(\s*&(?:mut )?self\b([^)]*)\)", f.read_text(), re.S):
            if re.search(r"\*mut (?:u\d+|i\d+|usize|bool)", m.group(1)):
                n += 1
    return n


PAIRS = [
    ("raft/server.h", "raft/src/server_h.rs",
     "Rust owns it; the C++ left is kernels and a pointer-holding shim"),
    ("raft/server.cc", "raft/src/server_cc.rs", ""),
    ("raft/service.cc", "raft/rt/src/service.rs",
     "one per lane: the C++ for hybrid, the Rust for MAKO_RAFT_LANE=rust"),
    ("raft/commo.cc", "raft/rt/src/transport.rs",
     "one per lane: the C++ for hybrid, the Rust for MAKO_RAFT_LANE=rust"),
    ("raft/server_seam_cpp.cc", "raft/rt/src/seam.rs",
     "the runtime seam, one per lane; exactly one is linked"),
    ("communicator.h", "raft/src/communicator_h.rs",
     "ONE source: the Rust is transpiled into the C++ both engines link"),
]


def body():
    o = []
    w = o.append
    w("# Raft C++ <-> Rust: what corresponds to what")
    w("")
    w("GENERATED by `scripts/gen_correspondence.py` -- do not edit; re-run it.")
    w("The numbers were hand-typed once and every one was wrong within a day, so")
    w("they are computed from the tree with the counting rule stated beside each.")
    w("")
    w("No commit hash here on purpose: embedding one makes this file stale on")
    w("every commit whether or not a number moved, and a `--check` that cries")
    w("wolf gets switched off. `--check` is the freshness guarantee.")
    w("")
    w("## Where each piece lives")
    w("")
    w("| C++ | lines | Rust | lines | state |")
    w("|---|---|---|---|---|")
    for cpp, rs, note in PAIRS:
        w(f"| `{cpp}` | {lines('src/deptran/' + cpp)} | `{rs}` | "
          f"{lines('src/deptran/' + rs)} | {note} |")
    w(f"| `rcc_rpc.h` (Raft slice) | — | `raft/rt/src/rpc.rs` | "
      f"{lines('src/deptran/raft/rt/src/rpc.rs')} | generated from `rcc_rpc.rpc`; "
      f"ids frozen in `raft/rpc_ids.txt` |")
    w("")
    w("`communicator_h.rs` is extracted from the HEADER, not the `.cc` --")
    w("`raft/rust-modules.toml` names `src/deptran/communicator.h` as its source.")
    w("")
    w("## How the boundary is crossed")
    w("")
    w("| direction | mechanism | count |")
    w("|---|---|---|")
    w(f"| C++ → Rust | prototypes in `raft/server_exports.h` | "
      f"{exports('src/deptran/raft/server_exports.h')} |")
    w(f"| C++ → Rust | prototypes in `raft/transport_exports.h` — the Rust lane only (raft_lane_rust.cc) |"
      f" {exports('src/deptran/raft/transport_exports.h')} |")
    w(f"| Rust → C++ | distinct `raft_*` kernels declared in `extern \"C\"` blocks under "
      f"`raft/src/` | {kernels()} |")
    w("")
    w("## Counted facts the prose below leans on")
    w("")
    w("| fact | count | counting rule |")
    w("|---|---|---|")
    w(f"| out-parameter methods | {out_params()} | a `self` receiver AND a "
      f"`*mut` scalar parameter. NOT a grep for `*mut u64`, which counts "
      f"kernel declarations and locals too |")
    w(f"| `raft_catch` sites | {catch_sites()} | CALL sites in `raft/server.cc`; "
      f"`grep -c` also counts the template definition |")
    w("")
    w("An export is a method of the Rust server the C++ shim calls. A kernel is")
    w("the other direction -- and most are C++ because of WHERE THE BOUNDARY SITS")
    w("today, not because Rust cannot express them. An earlier revision of this")
    w("file said kernels exist for \"the reactor, threads\"; both were wrong.")
    w("")
    w("| kernel group | why it is C++ | irreducible? |")
    w("|---|---|---|")
    w("| `raft_queue_wake_job`, `raft_spawn_heartbeat_loop`, `raft_fiber_sleep_us` "
      "| the Raft server runs on the C++ lane's reactor | **no** -- the Rust lane "
      "has one and `transport.rs` already uses it |")
    w("| `raft_spawn_apply_thread`, `raft_apply_thread_join` | "
      "`using RaftStdThread = ::std::thread` (`raft/server.h:336`) | "
      "**no** -- `std::thread::spawn` |")
    w("| `raft_monotonic_now_us` | it is `std::chrono::steady_clock` "
      "(`raft/server.cc:1325`) | **no** -- `std::time::Instant` |")
    w("| `raft_command_*`, `raft_byte_string_*` | `janus::Command` is Mako's "
      "object, put on at Submit and taken off at apply | yes, while Mako owns it |")
    w("| `raft_bind_commo` | `dynamic_cast` | yes -- no Rust spelling |")
    w("| the `raft_catch` sites | catching a C++ throw | yes |")
    w("| the four embedder `std::function`s | the embedder supplies them | yes |")
    w("")
    w("Not kernels at all, despite an earlier revision listing them: rocksdb and")
    w("yaml-cpp. No kernel includes either -- `raft/rocksdb_log_storage.hpp` is a")
    w("plain C++ storage backend the Rust never calls.")
    return o


def rest():
    """Everything after the generated tables is kept verbatim."""
    if not DOC.is_file():
        return []
    text = DOC.read_text().split("\n")
    for i, l in enumerate(text):
        if l.startswith("## How C++ idioms appear"):
            return text[i:]
    return []


def main():
    out = "\n".join(body() + [""] + rest()).rstrip() + "\n"
    if "--check" in sys.argv:
        if DOC.read_text() != out:
            sys.exit("cpp-rust-correspondence.md is stale; re-run "
                     "scripts/gen_correspondence.py")
        print(f"{DOC.name}: up to date")
        return 0
    DOC.write_text(out)
    print(f"wrote {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
