#!/usr/bin/env python3
"""Extract the Raft inline Rust DSL into the Stage 2 verification crate.

The extracted `.rs` files under src/deptran/raft/src are GENERATED by
concatenating each carrier's `#if RUSTYCPP_RUST` blocks; for those the inline
blocks remain the source of truth (schema 1 in rust-modules.toml). Modules with
`kind = "canonical"` (server_h.rs, server_cc.rs since F2.6) are the source
themselves: rustc compiles them into libraft.a and nothing is extracted.

  --mode rewrite   regenerate the .rs files and lib.rs in place
  --mode check     regenerate into a scratch dir and fail on any difference
                   from what is committed, so the crate can never silently
                   diverge from the blocks it came from

NOTE on ordering: the transpiler authenticates against the nearest Cargo.toml
and reads its `[lib] path`, so src/deptran/raft/src/lib.rs must EXIST before
any extraction runs. This script seeds a placeholder if it is missing.
"""
from __future__ import annotations

import argparse
import filecmp
import os
from pathlib import Path
import subprocess
import sys
import tomllib

HEADER = (
    "// GENERATED by `bash scripts/raft_dsl.sh --rewrite` from the inline\n"
    "// `#if RUSTYCPP_RUST` blocks listed in ../rust-modules.toml.\n"
    "// Do not edit: edit the blocks in the carriers instead.\n"
    "//\n"
    "// This crate is a VERIFICATION view of the DSL, not a production\n"
    "// provider. Production compiles the committed generated C++ next to\n"
    "// each block. See docs/stage2_current_progress.txt.\n\n"
)


def load_modules(manifest: Path) -> list[dict]:
    data = tomllib.loads(manifest.read_text())
    if data.get("schema_version") != 1:
        raise SystemExit(
            f"{manifest}: expected schema_version = 1 (extraction); "
            f"got {data.get('schema_version')!r}"
        )
    mods = data.get("module") or []
    if not mods:
        raise SystemExit(f"{manifest}: no [[module]] entries")
    return mods


def emit(transpiler: Path, source: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [str(transpiler), "inline-rust", "--emit-rust", str(out),
         "--files", str(source)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(
            f"extraction failed for {source}:\n{proc.stderr.strip()}"
        )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=("rewrite", "check"), required=True)
    ap.add_argument("--transpiler", type=Path, required=True)
    ap.add_argument("--manifest", type=Path, required=True)
    ap.add_argument("--scratch", type=Path, required=True)
    args = ap.parse_args()

    root = args.manifest.parent
    mods = load_modules(args.manifest)
    repo = Path(__file__).resolve().parent.parent

    lib = root / "src" / "lib.rs"
    if not lib.exists():
        lib.parent.mkdir(parents=True, exist_ok=True)
        lib.write_text("// placeholder; regenerated by raft_dsl.sh --rewrite\n")

    names: list[str] = []
    gates: dict[str, str] = {}
    staged: list[tuple[Path, Path]] = []
    canonical: list[Path] = []
    for m in mods:
        committed = repo / m["output"]
        name = committed.stem
        names.append(name)
        if m.get("cfg_feature"):
            gates[name] = m["cfg_feature"]
        if m.get("kind") == "canonical":
            # Canonical Rust (F2.6): the .rs IS the source. Nothing to emit; it
            # only has to exist, and lib.rs has to name it.
            canonical.append(committed)
            continue
        source = repo / m["source"]
        target = committed if args.mode == "rewrite" else args.scratch / committed.name
        emit(args.transpiler, source, target)
        staged.append((committed, target))

    def mod_line(n: str) -> str:
        gate = f'#[cfg(feature = "{gates[n]}")]\n' if n in gates else ""
        return f"{gate}pub mod {n};\n"

    lib_text = HEADER + "".join(mod_line(n) for n in sorted(names))

    if args.mode == "rewrite":
        lib.write_text(lib_text)
        print(f"raft crate: regenerated {len(names)} module(s) + lib.rs")
        return 0

    drift: list[str] = []
    for committed in canonical:
        if not committed.exists():
            drift.append(f"missing canonical module: {committed.relative_to(repo)}")
    for committed, fresh in staged:
        if not committed.exists():
            drift.append(f"missing committed module: {committed.relative_to(repo)}")
        elif not filecmp.cmp(committed, fresh, shallow=False):
            drift.append(f"drift: {committed.relative_to(repo)}")
    if lib.read_text() != lib_text:
        drift.append(f"drift: {lib.relative_to(repo)}")

    # An extracted .rs with no manifest entry is orphan output.
    src_dir = root / "src"
    expected = {Path(repo / m["output"]).name for m in mods} | {"lib.rs"}
    for found in sorted(p.name for p in src_dir.glob("*.rs")):
        if found not in expected:
            drift.append(f"orphan module not in manifest: src/{found}")

    if drift:
        for d in drift:
            print(f"  {d}", file=sys.stderr)
        print(
            "the crate is generated from the inline blocks; run "
            "`bash scripts/raft_dsl.sh --rewrite` and commit the result",
            file=sys.stderr,
        )
        return 1

    print(f"raft crate: {len(names)} module(s) + lib.rs, no drift")
    return 0


if __name__ == "__main__":
    sys.exit(main())
