#!/bin/bash

# Thread-count sweep across ALL three replication backends (Paxos, Multi-Raft,
# Single-Raft) one after another, then prints a side-by-side comparison table
# generated by scripts/process_scalability_results.py.
#
# Usage:
#   bash scripts/sweep_all.sh
#   bash scripts/sweep_all.sh --threads "1 2 4 8 16 24" --runs 3 --batch-size 400
#   bash scripts/sweep_all.sh --backends "paxos raft-single"   # subset
#   bash scripts/sweep_all.sh --skip-build                     # reuse existing binaries

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

THREADS="1 2 4 8 16 24"
RUNS=3
BATCH_SIZE=400
BACKENDS="paxos raft-multi raft-single"
SKIP_BUILD=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --threads)    THREADS="$2"; shift 2 ;;
        --runs)       RUNS="$2"; shift 2 ;;
        --batch-size) BATCH_SIZE="$2"; shift 2 ;;
        --backends)   BACKENDS="$2"; shift 2 ;;
        --skip-build) SKIP_BUILD=1; shift ;;
        -h|--help)    sed -n '3,12p' "$0"; exit 0 ;;
        *)            echo "Unknown arg: $1"; exit 1 ;;
    esac
done

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
COMBINED_DIR="${REPO_ROOT}/results/benchmarks/combined/sweep_all_${TIMESTAMP}"
COMPARISON_FILE="${COMBINED_DIR}/comparison_table.txt"
LATEST_LINK="${REPO_ROOT}/results/benchmarks/combined/sweep_all_latest"
mkdir -p "$COMBINED_DIR"
ln -sfn "$COMBINED_DIR" "$LATEST_LINK"

echo "============================================================"
echo "  Mako Combined Thread Sweep (all backends)"
echo "  Backends:   $BACKENDS"
echo "  Threads:    $THREADS"
echo "  Runs/conf:  $RUNS"
echo "  Batch size: $BATCH_SIZE"
echo "  Output:     $COMBINED_DIR/"
echo "  Started:    $(date)"
echo "============================================================"

SUCCEEDED=""
FAILED=""

for backend in $BACKENDS; do
    echo ""
    echo "############################################################"
    echo "  Running sweep: $backend"
    echo "############################################################"

    case "$backend" in
        paxos)        wrapper="scripts/sweep_paxos.sh" ;;
        raft-multi)   wrapper="scripts/sweep_raft_multi.sh" ;;
        raft-single)  wrapper="scripts/sweep_raft_single.sh" ;;
        *) echo "ERROR: unknown backend '$backend'"; FAILED="$FAILED $backend"; continue ;;
    esac

    args=(--threads "$THREADS" --runs "$RUNS" --batch-size "$BATCH_SIZE")
    [ "$SKIP_BUILD" -eq 1 ] && args+=(--skip-build)

    if bash "$wrapper" "${args[@]}"; then
        SUCCEEDED="$SUCCEEDED $backend"
    else
        echo "ERROR: $backend sweep failed."
        FAILED="$FAILED $backend"
    fi
done

# ============================================================
#  Build comparison table from each backend's latest CSV
# ============================================================
echo ""
echo "############################################################"
echo "  Generating comparison table"
echo "############################################################"

PY_ARGS=()
for backend in $SUCCEEDED; do
    csv="${REPO_ROOT}/results/benchmarks/${backend}/scalability_latest/results.csv"
    if [ ! -f "$csv" ]; then
        echo "WARNING: missing CSV for $backend ($csv) — skipping in comparison"
        continue
    fi
    case "$backend" in
        paxos)       PY_ARGS+=(--paxos       "$csv") ;;
        raft-multi)  PY_ARGS+=(--raft-multi  "$csv") ;;
        raft-single) PY_ARGS+=(--raft-single "$csv") ;;
    esac
    # Snapshot each backend's CSV into the combined dir for archival
    cp "$csv" "${COMBINED_DIR}/${backend}_results.csv"
done

if [ ${#PY_ARGS[@]} -gt 0 ]; then
    python3 scripts/process_scalability_results.py \
        "${PY_ARGS[@]}" \
        --output "$COMPARISON_FILE"
    echo ""
    echo "------------------------------------------------------------"
    echo "  COMPARISON TABLE"
    echo "------------------------------------------------------------"
    cat "$COMPARISON_FILE"
else
    echo "No backend results available to compare."
fi

echo ""
echo "############################################################"
echo "  ALL SWEEPS COMPLETE — $(date)"
echo "  Succeeded:$SUCCEEDED"
[ -n "$FAILED" ] && echo "  Failed:   $FAILED"
echo "  Combined output: $COMBINED_DIR/"
echo "  Latest link:     $LATEST_LINK"
echo "  Comparison:      $COMPARISON_FILE"
echo "############################################################"
