// @generated by scripts/rpcgen_rust.py from src/deptran/rcc_rpc.rpc -- do not edit.
//
// The Rust counterpart of the generated C++ in src/deptran/rcc_rpc.h.
// Handler bodies are NOT here: they are hand-written, the same split
// C++ uses between RaftService and RaftServiceImpl.

#![allow(dead_code)]

use srpc::client::{AsyncReplyCallback, Client};
use srpc::serializable::{
    deserialize_bytes_with, make_source_proxy_buffer, serialize_bytes,
    BinaryReadArchive, BinaryWriteArchive, BufferSource, Deserialize,
    Serialize,
};
use srpc::server::{
    reject_malformed_request, Request, Server, WeakServerConnection,
};

/// A C++ `std::string` as this wire carries it: a v64 length, then the
/// raw bytes. Deliberately not `String`, whose decoder rejects non-UTF-8
/// input -- and a snapshot is binary.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct WireBytes(pub Vec<u8>);

impl Serialize for WireBytes {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        // SAFETY: the Vec is live for the call; serialize_bytes reads len bytes.
        unsafe { serialize_bytes(self.0.as_ptr(), self.0.len(), ar) }
    }
}

impl Deserialize for WireBytes {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        // SAFETY: resize and data describe this Vec's own storage.
        unsafe {
            deserialize_bytes_with(&mut self.0, ar,
                |v: &mut Vec<u8>, n: usize| v.resize(n, 0u8),
                |v: &mut Vec<u8>| v.as_mut_ptr());
        }
    }
}

/// Wire ids. Randomly assigned once by rpcgen and preserved only by
/// scraping the previously generated header, so they are the wire
/// contract -- never regenerate them.
pub mod rpc_id {
    pub const APPENDENTRIES: i32 = 0x3935326f;
    pub const EMPTYAPPENDENTRIES: i32 = 0x6e089268;
    pub const INSTALLSNAPSHOT: i32 = 0x5276442f;
    pub const VOTE: i32 = 0x2802b911;
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteRequest {
    pub lst_log_idx: u64,
    pub lst_log_term: i64,
    pub site_id: u16,
    pub cur_term: i64,
}

impl Serialize for VoteRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.lst_log_idx.serialize(ar);
        self.lst_log_term.serialize(ar);
        self.site_id.serialize(ar);
        self.cur_term.serialize(ar);
    }
}

impl Deserialize for VoteRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.lst_log_idx.deserialize(ar);
        self.lst_log_term.deserialize(ar);
        self.site_id.deserialize(ar);
        self.cur_term.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteResponse {
    pub max_ballot: i64,
    pub vote_granted: i8,
}

impl Serialize for VoteResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.max_ballot.serialize(ar);
        self.vote_granted.serialize(ar);
    }
}

impl Deserialize for VoteResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.max_ballot.deserialize(ar);
        self.vote_granted.deserialize(ar);
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct AppendEntriesRequest {
    pub slot: u64,
    pub ballot: i64,
    pub leader_current_term: u64,
    pub leader_site_id: u16,
    pub leader_prev_log_index: u64,
    pub leader_prev_log_term: u64,
    pub leader_commit_index: u64,
    pub cmd: Vec<u8>,
    pub leader_next_log_term: u64,
}

impl Serialize for AppendEntriesRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.slot.serialize(ar);
        self.ballot.serialize(ar);
        self.leader_current_term.serialize(ar);
        self.leader_site_id.serialize(ar);
        self.leader_prev_log_index.serialize(ar);
        self.leader_prev_log_term.serialize(ar);
        self.leader_commit_index.serialize(ar);
        // SAFETY: `cmd` is a live Vec; write_bytes reads len bytes of it.
        unsafe { ar.write_bytes(self.cmd.as_ptr(), self.cmd.len()) };
        self.leader_next_log_term.serialize(ar);
    }
}

// AppendEntriesRequest has an opaque field (cmd), so it
// decodes from the whole frame rather than a streaming archive.

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AppendEntriesResponse {
    pub follower_append_ok: u64,
    pub follower_current_term: u64,
    pub follower_last_log_index: u64,
}

impl Serialize for AppendEntriesResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.follower_append_ok.serialize(ar);
        self.follower_current_term.serialize(ar);
        self.follower_last_log_index.serialize(ar);
    }
}

impl Deserialize for AppendEntriesResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.follower_append_ok.deserialize(ar);
        self.follower_current_term.deserialize(ar);
        self.follower_last_log_index.deserialize(ar);
    }
}

impl AppendEntriesRequest {
    /// Decode from the whole request frame.
    ///
    /// `cmd` is opaque to Rust -- C++ owns its
    /// encoding and it carries no length -- but its extent is
    /// arithmetic: it runs from byte 50 to `len - 8`,
    /// because every field around it is fixed-width. The bytes
    /// are copied verbatim and handed back to C++ untouched.
    pub fn from_body(body: &[u8]) -> Option<Self> {
        if body.len() < 50 + 8 {
            return None;
        }
        let mut src = BufferSource::new(body.as_ptr(), body.len());
        let mut ar = BinaryReadArchive::new(unsafe {
            make_source_proxy_buffer(&raw mut src)
        });
        let mut out = Self::default();
        out.slot.deserialize(&mut ar);
        out.ballot.deserialize(&mut ar);
        out.leader_current_term.deserialize(&mut ar);
        out.leader_site_id.deserialize(&mut ar);
        out.leader_prev_log_index.deserialize(&mut ar);
        out.leader_prev_log_term.deserialize(&mut ar);
        out.leader_commit_index.deserialize(&mut ar);
        if ar.failed() {
            return None;
        }
        out.cmd =
            body[50..body.len() - 8].to_vec();
        let mut tail = body.len() - 8;
        out.leader_next_log_term = u64::from_le_bytes(
            body[tail..tail + 8].try_into().ok()?,
        );
        tail += 8;
        let _ = tail;
        Some(out)
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesRequest {
    pub slot: u64,
    pub ballot: i64,
    pub leader_current_term: u64,
    pub leader_site_id: u16,
    pub leader_prev_log_index: u64,
    pub leader_prev_log_term: u64,
    pub leader_commit_index: u64,
}

impl Serialize for EmptyAppendEntriesRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.slot.serialize(ar);
        self.ballot.serialize(ar);
        self.leader_current_term.serialize(ar);
        self.leader_site_id.serialize(ar);
        self.leader_prev_log_index.serialize(ar);
        self.leader_prev_log_term.serialize(ar);
        self.leader_commit_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.slot.deserialize(ar);
        self.ballot.deserialize(ar);
        self.leader_current_term.deserialize(ar);
        self.leader_site_id.deserialize(ar);
        self.leader_prev_log_index.deserialize(ar);
        self.leader_prev_log_term.deserialize(ar);
        self.leader_commit_index.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesResponse {
    pub follower_append_ok: u64,
    pub follower_current_term: u64,
    pub follower_last_log_index: u64,
}

impl Serialize for EmptyAppendEntriesResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.follower_append_ok.serialize(ar);
        self.follower_current_term.serialize(ar);
        self.follower_last_log_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.follower_append_ok.deserialize(ar);
        self.follower_current_term.deserialize(ar);
        self.follower_last_log_index.deserialize(ar);
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotRequest {
    pub term: u64,
    pub leader_id: u64,
    pub last_included_index: u64,
    pub last_included_term: u64,
    pub data: WireBytes,
}

impl Serialize for InstallSnapshotRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term.serialize(ar);
        self.leader_id.serialize(ar);
        self.last_included_index.serialize(ar);
        self.last_included_term.serialize(ar);
        self.data.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term.deserialize(ar);
        self.leader_id.deserialize(ar);
        self.last_included_index.deserialize(ar);
        self.last_included_term.deserialize(ar);
        self.data.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotResponse {
    pub term_out: u64,
}

impl Serialize for InstallSnapshotResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term_out.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term_out.deserialize(ar);
    }
}

/// The Raft service. Implement this; `dispatch` below routes
/// to it. An `Err(code)` is replied as that code with no body.
pub trait RaftHandler: Send + Sync {
    fn vote(&self, req: &VoteRequest) -> Result<VoteResponse, i32>;
    fn append_entries(&self, req: &AppendEntriesRequest) -> Result<AppendEntriesResponse, i32>;
    fn empty_append_entries(&self, req: &EmptyAppendEntriesRequest) -> Result<EmptyAppendEntriesResponse, i32>;
    fn install_snapshot(&self, req: &InstallSnapshotRequest) -> Result<InstallSnapshotResponse, i32>;
}

/// Register every rpc id this service answers. Call this from
/// `Service::__reg_to__`; a nonzero return is srpc's error code.
pub fn register(server: &mut Server, svc_index: usize) -> i32 {
    let ret = server.reg_fast_rpc(rpc_id::VOTE, svc_index);
    if ret != 0 {
        return ret;
    }
    let ret = server.reg_fast_rpc(rpc_id::APPENDENTRIES, svc_index);
    if ret != 0 {
        return ret;
    }
    let ret = server.reg_fast_rpc(rpc_id::EMPTYAPPENDENTRIES, svc_index);
    if ret != 0 {
        return ret;
    }
    let ret = server.reg_fast_rpc(rpc_id::INSTALLSNAPSHOT, svc_index);
    if ret != 0 {
        return ret;
    }
    0
}

/// Route one request to `handler`. Call this from `Service::__dispatch__`.
/// A request's ARGUMENT bytes: what the streaming decoders read through
/// `req.src`, which starts after the frame header. `req.body` holds that
/// header too, so an opaque field bounded by arithmetic must be measured
/// from here, not from `body[0]` -- measuring from the body put every
/// field five bytes off and misparsed every AppendEntries over TCP.
fn args_of(req: &Request) -> &[u8] {
    let src = &req.src;
    // SAFETY: src describes a live buffer (req.body) of len_ bytes, and
    // pos_ <= len_; the slice borrows it for req's lifetime.
    unsafe { core::slice::from_raw_parts(src.data_.add(src.pos_), src.len_ - src.pos_) }
}

pub fn dispatch<H: RaftHandler>(
    handler: &H,
    rpc_id: i32,
    req: &Request,
    weak_sconn: &WeakServerConnection,
) {
    match rpc_id {
        rpc_id::VOTE => {
            let mut typed = VoteRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.vote(&typed));
        }
        rpc_id::APPENDENTRIES => {
            let Some(typed) = AppendEntriesRequest::from_body(args_of(req)) else {
                reject_malformed_request(req, weak_sconn);
                return;
            };
            reply_with(weak_sconn, req, handler.append_entries(&typed));
        }
        rpc_id::EMPTYAPPENDENTRIES => {
            let mut typed = EmptyAppendEntriesRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.empty_append_entries(&typed));
        }
        rpc_id::INSTALLSNAPSHOT => {
            let mut typed = InstallSnapshotRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.install_snapshot(&typed));
        }
        // Unknown id: ignore, matching the generated C++ dispatch.
        _ => {}
    }
}

/// Serialize a handler result back to the caller. Err(code) replies
/// that code with no body; Ok(resp) replies 0 with the fields.
fn reply_with<R: Serialize + 'static>(
    weak_sconn: &WeakServerConnection,
    req: &Request,
    result: Result<R, i32>,
) {
    let Some(sconn) = weak_sconn.upgrade() else { return };
    match result {
        Err(code) => sconn.reply(req, code, None),
        Ok(resp) => sconn.reply(
            req,
            0,
            Some(Box::new(move |ar: &mut BinaryWriteArchive| {
                resp.serialize(ar);
            })),
        ),
    }
}

/// Client side. One method per RPC, mirroring RaftProxy in
/// the generated C++ header.
pub struct RaftProxy<'a> {
    pub client: &'a Client,
}

impl<'a> RaftProxy<'a> {
    pub fn vote_async(
        &self,
        req: &VoteRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = *req;
        self.client.request_async(
            rpc_id::VOTE,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

    pub fn append_entries_async(
        &self,
        req: AppendEntriesRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = req;
        self.client.request_async(
            rpc_id::APPENDENTRIES,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

    pub fn empty_append_entries_async(
        &self,
        req: &EmptyAppendEntriesRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = *req;
        self.client.request_async(
            rpc_id::EMPTYAPPENDENTRIES,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

    pub fn install_snapshot_async(
        &self,
        req: InstallSnapshotRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = req;
        self.client.request_async(
            rpc_id::INSTALLSNAPSHOT,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

}

