#pragma once

// rrr's logging, reachable from a Raft DSL body.
//
// WHY THIS EXISTS
//
// `rrr::Log_info` and friends (src/rrr_log.h) are variadic FUNCTION TEMPLATES
// taking `std::format_string<Args...>`, not macros, so there is nothing
// preprocessor-shaped in the way. What is in the way is Rust: it has no
// variadic generics, so a DSL body cannot name one function that takes any
// number of arguments. The remaining 160 Log_ call sites in server.cc are
// therefore the single largest thing blocking method bodies from converting.
//
// The fix is one name per (level, arity). Rust declares each as an ordinary
// generic function with that many type parameters; C++ defines each as a
// variadic template that forwards to the real logger. Because the C++
// parameter is still `std::format_string<Args...>`, the compile-time format
// check happens at the DSL call site exactly as it does today -- a wrong
// placeholder count is still a compile error, not a runtime surprise.
//
// The level check also still short-circuits: these are inline forwarders, so
// `Log_debug`'s `if (Log::DEBUG <= Log::level_now())` guard is evaluated
// before the arguments are formatted, which is the property src/rrr_log.h
// exists to preserve.
//
// Arities 0..10 cover every Raft call site (the widest is a ten-argument
// Log_info in HeartbeatPhase1). The Rust half is generated by the
// `raft_log_shims!` macro in src/rrr/rusty-rustc/src/lib.rs and must stay in
// step with this file.

#include <format>
#include <utility>

#include "../../rrr_log.h"

namespace rusty {

#define RAFT_DSL_LOG_SHIM(shim_name, rrr_name)                                \
  template <typename... Args>                                                 \
  inline void shim_name(std::format_string<Args...> fmt, Args&&... args) {    \
    ::rrr::rrr_name(fmt, std::forward<Args>(args)...);                        \
  }

#define RAFT_DSL_LOG_LEVEL(level)                                             \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_0, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_1, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_2, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_3, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_4, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_5, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_6, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_7, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_8, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_9, Log_##level)                        \
  RAFT_DSL_LOG_SHIM(raft_log_##level##_10, Log_##level)

RAFT_DSL_LOG_LEVEL(debug)
RAFT_DSL_LOG_LEVEL(info)
RAFT_DSL_LOG_LEVEL(warn)
RAFT_DSL_LOG_LEVEL(error)

#undef RAFT_DSL_LOG_LEVEL
#undef RAFT_DSL_LOG_SHIM

}  // namespace rusty
