#!/usr/bin/env python3
"""Freeze a spec version: export the patch series and write SPEC_VERSION.toml.

    scripts/verus/spec_manifest.py TAG VERIFIED_COUNT RESULT_LOG

Run after tagging TAG (e.g. raft-spec-v1) on $GLR's mako-spec branch and
running the full-crate check whose log is RESULT_LOG. It regenerates
src/deptran/raft/verus/spec/patches/ with `git format-patch BASE..TAG`,
computes the sha256 of every statement-bearing file at TAG
(docs/verus/modification-plan.md §4.5: whole files, decided in Phase 0), and
writes the manifest that scripts/verus/verify_spec.sh checks. VERIFIED_COUNT
must match the result line in RESULT_LOG.
"""
import hashlib
import os
import re
import shutil
import subprocess
import sys

BASE = "d7e04ed7"
BRANCH = "mako-spec"
RAFT = "src/protocol/Raft/"
# The atomic spec, the method layer, and the safety property with its guard
# copy (plan §4.5). Each file defines part of what the certificate says.
HASHED = [RAFT + f for f in (
    "types.rs", "raft.rs", "raft_composite.rs", "raft_refinement.rs", "read_index.rs",
    "membership.rs", "ghost_log.rs", "ghost_log_compose.rs",
    "refinement_proof/invariants.rs", "refinement_proof/state_machine.rs")]


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    tag, verified, log = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    glr = os.environ["GLR"]
    verus = os.environ["VERUS_PIN"]
    repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    spec_dir = os.path.join(repo, "src/deptran/raft/verus/spec")
    text = open(log).read()
    r = re.findall(r"verification results:: (\d+) verified, (\d+) errors", text)
    if not r or int(r[-1][0]) != verified or int(r[-1][1]) != 0:
        print(f"spec_manifest: {log} does not record {verified} verified, 0 errors: {r[-1:] }")
        return 1

    def git(*a, binary=False):
        return subprocess.run(["git", "-C", glr, *a], check=True, capture_output=True,
                              text=not binary).stdout

    patches = os.path.join(spec_dir, "patches")
    shutil.rmtree(patches, ignore_errors=True)
    os.makedirs(patches)
    names = []
    if git("rev-list", f"{BASE}..{tag}").strip():
        out = git("format-patch", "--no-signature", "--zero-commit", f"{BASE}..{tag}", "-o", patches)
        names = [os.path.basename(p) for p in out.split()]
    version = subprocess.run([verus, "--version"], capture_output=True, text=True).stdout
    vline = re.search(r"Version: (\S+)", version).group(1)
    tool = re.search(r"Toolchain: (\S+)", version).group(1)
    lines = [
        "# Frozen spec version. Generated by scripts/verus/spec_manifest.py;",
        "# checked by scripts/verus/verify_spec.sh. Do not edit by hand.",
        f'upstream = "{git("remote", "get-url", "origin").strip()}"',
        f'base_commit = "{BASE}"',
        f'branch = "{BRANCH}"',
        f'tag = "{tag}"',
        f'tag_commit = "{git("rev-parse", tag + "^{commit}").strip()}"',
        "patches = [" + ", ".join(f'"{n}"' for n in names) + "]",
        f'verus_version = "{vline}"',
        f'toolchain = "{tool}"',
        'verify_command = "verus --crate-type=dylib --expand-errors src/lib.rs (in $GLR)"',
        f"verified = {verified}",
        f'result = "{verified} verified, 0 errors"',
        'hash_scope = "whole files"',
        "",
        "[sha256]",
    ]
    for path in HASHED:
        blob = git("show", f"{tag}:{path}", binary=True)
        lines.append(f'"{path}" = "{hashlib.sha256(blob).hexdigest()}"')
    with open(os.path.join(spec_dir, "SPEC_VERSION.toml"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {spec_dir}/SPEC_VERSION.toml and {len(names)} patch(es)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
