// @generated by scripts/rpcgen_rust.py from src/deptran/rcc_rpc.rpc -- do not edit.
//
// The Rust counterpart of the generated C++ in src/deptran/rcc_rpc.h.
// Handler bodies are NOT here: they are hand-written, the same split
// C++ uses between RaftService and RaftServiceImpl.

#![allow(dead_code)]

use srpc::serializable::{
    BinaryReadArchive, BinaryWriteArchive, Deserialize, Serialize,
};

/// Wire ids. Randomly assigned once by rpcgen and preserved only by
/// scraping the previously generated header, so they are the wire
/// contract -- never regenerate them.
pub mod rpc_id {
    pub const APPENDENTRIES: i32 = 0x3935326f;
    pub const EMPTYAPPENDENTRIES: i32 = 0x6e089268;
    pub const INSTALLSNAPSHOT: i32 = 0x5276442f;
    pub const VOTE: i32 = 0x2802b911;
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteRequest {
    pub lst_log_idx: u64,
    pub lst_log_term: i64,
    pub site_id: u16,
    pub cur_term: i64,
}

impl Serialize for VoteRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.lst_log_idx.serialize(ar);
        self.lst_log_term.serialize(ar);
        self.site_id.serialize(ar);
        self.cur_term.serialize(ar);
    }
}

impl Deserialize for VoteRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.lst_log_idx.deserialize(ar);
        self.lst_log_term.deserialize(ar);
        self.site_id.deserialize(ar);
        self.cur_term.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteResponse {
    pub max_ballot: i64,
    pub vote_granted: i8,
}

impl Serialize for VoteResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.max_ballot.serialize(ar);
        self.vote_granted.serialize(ar);
    }
}

impl Deserialize for VoteResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.max_ballot.deserialize(ar);
        self.vote_granted.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesRequest {
    pub slot: u64,
    pub ballot: i64,
    pub leader_current_term: u64,
    pub leader_site_id: u16,
    pub leader_prev_log_index: u64,
    pub leader_prev_log_term: u64,
    pub leader_commit_index: u64,
}

impl Serialize for EmptyAppendEntriesRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.slot.serialize(ar);
        self.ballot.serialize(ar);
        self.leader_current_term.serialize(ar);
        self.leader_site_id.serialize(ar);
        self.leader_prev_log_index.serialize(ar);
        self.leader_prev_log_term.serialize(ar);
        self.leader_commit_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.slot.deserialize(ar);
        self.ballot.deserialize(ar);
        self.leader_current_term.deserialize(ar);
        self.leader_site_id.deserialize(ar);
        self.leader_prev_log_index.deserialize(ar);
        self.leader_prev_log_term.deserialize(ar);
        self.leader_commit_index.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesResponse {
    pub follower_append_ok: u64,
    pub follower_current_term: u64,
    pub follower_last_log_index: u64,
}

impl Serialize for EmptyAppendEntriesResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.follower_append_ok.serialize(ar);
        self.follower_current_term.serialize(ar);
        self.follower_last_log_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.follower_append_ok.deserialize(ar);
        self.follower_current_term.deserialize(ar);
        self.follower_last_log_index.deserialize(ar);
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotRequest {
    pub term: u64,
    pub leader_id: u64,
    pub last_included_index: u64,
    pub last_included_term: u64,
    pub data: String,
}

impl Serialize for InstallSnapshotRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term.serialize(ar);
        self.leader_id.serialize(ar);
        self.last_included_index.serialize(ar);
        self.last_included_term.serialize(ar);
        self.data.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term.deserialize(ar);
        self.leader_id.deserialize(ar);
        self.last_included_index.deserialize(ar);
        self.last_included_term.deserialize(ar);
        self.data.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotResponse {
    pub term_out: u64,
}

impl Serialize for InstallSnapshotResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term_out.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term_out.deserialize(ar);
    }
}

/// The Raft service. Implement this; the dispatch below
/// routes to it.
pub trait RaftService: Send + Sync {
    fn vote(&self, req: &VoteRequest) -> VoteResponse;
    fn empty_append_entries(&self, req: &EmptyAppendEntriesRequest) -> EmptyAppendEntriesResponse;
    fn install_snapshot(&self, req: &InstallSnapshotRequest) -> InstallSnapshotResponse;
}

