// @generated by scripts/rpcgen_rust.py from src/deptran/rcc_rpc.rpc -- do not edit.
//
// The Rust counterpart of the generated C++ in src/deptran/rcc_rpc.h.
// Handler bodies are NOT here: they are hand-written, the same split
// C++ uses between RaftService and RaftServiceImpl.

#![allow(dead_code)]

use srpc::client::{AsyncReplyCallback, Client};
use srpc::serializable::{
    make_source_proxy_buffer, BinaryReadArchive, BinaryWriteArchive,
    Deserialize, Serialize,
};
use srpc::server::{
    reject_malformed_request, Request, WeakServerConnection,
};

/// Wire ids. Randomly assigned once by rpcgen and preserved only by
/// scraping the previously generated header, so they are the wire
/// contract -- never regenerate them.
pub mod rpc_id {
    pub const APPENDENTRIES: i32 = 0x3935326f;
    pub const EMPTYAPPENDENTRIES: i32 = 0x6e089268;
    pub const INSTALLSNAPSHOT: i32 = 0x5276442f;
    pub const VOTE: i32 = 0x2802b911;
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteRequest {
    pub lst_log_idx: u64,
    pub lst_log_term: i64,
    pub site_id: u16,
    pub cur_term: i64,
}

impl Serialize for VoteRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.lst_log_idx.serialize(ar);
        self.lst_log_term.serialize(ar);
        self.site_id.serialize(ar);
        self.cur_term.serialize(ar);
    }
}

impl Deserialize for VoteRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.lst_log_idx.deserialize(ar);
        self.lst_log_term.deserialize(ar);
        self.site_id.deserialize(ar);
        self.cur_term.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VoteResponse {
    pub max_ballot: i64,
    pub vote_granted: i8,
}

impl Serialize for VoteResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.max_ballot.serialize(ar);
        self.vote_granted.serialize(ar);
    }
}

impl Deserialize for VoteResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.max_ballot.deserialize(ar);
        self.vote_granted.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesRequest {
    pub slot: u64,
    pub ballot: i64,
    pub leader_current_term: u64,
    pub leader_site_id: u16,
    pub leader_prev_log_index: u64,
    pub leader_prev_log_term: u64,
    pub leader_commit_index: u64,
}

impl Serialize for EmptyAppendEntriesRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.slot.serialize(ar);
        self.ballot.serialize(ar);
        self.leader_current_term.serialize(ar);
        self.leader_site_id.serialize(ar);
        self.leader_prev_log_index.serialize(ar);
        self.leader_prev_log_term.serialize(ar);
        self.leader_commit_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.slot.deserialize(ar);
        self.ballot.deserialize(ar);
        self.leader_current_term.deserialize(ar);
        self.leader_site_id.deserialize(ar);
        self.leader_prev_log_index.deserialize(ar);
        self.leader_prev_log_term.deserialize(ar);
        self.leader_commit_index.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EmptyAppendEntriesResponse {
    pub follower_append_ok: u64,
    pub follower_current_term: u64,
    pub follower_last_log_index: u64,
}

impl Serialize for EmptyAppendEntriesResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.follower_append_ok.serialize(ar);
        self.follower_current_term.serialize(ar);
        self.follower_last_log_index.serialize(ar);
    }
}

impl Deserialize for EmptyAppendEntriesResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.follower_append_ok.deserialize(ar);
        self.follower_current_term.deserialize(ar);
        self.follower_last_log_index.deserialize(ar);
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotRequest {
    pub term: u64,
    pub leader_id: u64,
    pub last_included_index: u64,
    pub last_included_term: u64,
    pub data: String,
}

impl Serialize for InstallSnapshotRequest {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term.serialize(ar);
        self.leader_id.serialize(ar);
        self.last_included_index.serialize(ar);
        self.last_included_term.serialize(ar);
        self.data.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotRequest {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term.deserialize(ar);
        self.leader_id.deserialize(ar);
        self.last_included_index.deserialize(ar);
        self.last_included_term.deserialize(ar);
        self.data.deserialize(ar);
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InstallSnapshotResponse {
    pub term_out: u64,
}

impl Serialize for InstallSnapshotResponse {
    fn serialize(&self, ar: &mut BinaryWriteArchive) {
        self.term_out.serialize(ar);
    }
}

impl Deserialize for InstallSnapshotResponse {
    fn deserialize(&mut self, ar: &mut BinaryReadArchive) {
        self.term_out.deserialize(ar);
    }
}

/// The Raft service. Implement this; `dispatch` below routes
/// to it. An `Err(code)` is replied as that code with no body.
pub trait RaftHandler: Send + Sync {
    fn vote(&self, req: &VoteRequest) -> Result<VoteResponse, i32>;
    fn empty_append_entries(&self, req: &EmptyAppendEntriesRequest) -> Result<EmptyAppendEntriesResponse, i32>;
    fn install_snapshot(&self, req: &InstallSnapshotRequest) -> Result<InstallSnapshotResponse, i32>;
}

/// Route one request to `handler`. Call this from `Service::__dispatch__`.
pub fn dispatch<H: RaftHandler>(
    handler: &H,
    rpc_id: i32,
    req: &Request,
    weak_sconn: &WeakServerConnection,
) {
    match rpc_id {
        rpc_id::VOTE => {
            let mut typed = VoteRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.vote(&typed));
        }
        rpc_id::EMPTYAPPENDENTRIES => {
            let mut typed = EmptyAppendEntriesRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.empty_append_entries(&typed));
        }
        rpc_id::INSTALLSNAPSHOT => {
            let mut typed = InstallSnapshotRequest::default();
            let mut ar = BinaryReadArchive::new(unsafe {
                make_source_proxy_buffer(&req.src as *const _ as *mut _)
            });
            typed.deserialize(&mut ar);
            if ar.failed() {
                reject_malformed_request(req, weak_sconn);
                return;
            }
            reply_with(weak_sconn, req, handler.install_snapshot(&typed));
        }
        // Unknown id: ignore, matching the generated C++ dispatch.
        _ => {}
    }
}

/// Serialize a handler result back to the caller. Err(code) replies
/// that code with no body; Ok(resp) replies 0 with the fields.
fn reply_with<R: Serialize + 'static>(
    weak_sconn: &WeakServerConnection,
    req: &Request,
    result: Result<R, i32>,
) {
    let Some(sconn) = weak_sconn.upgrade() else { return };
    match result {
        Err(code) => sconn.reply(req, code, None),
        Ok(resp) => sconn.reply(
            req,
            0,
            Some(Box::new(move |ar: &mut BinaryWriteArchive| {
                resp.serialize(ar);
            })),
        ),
    }
}

/// Client side. One method per RPC, mirroring RaftProxy in
/// the generated C++ header.
pub struct RaftProxy<'a> {
    pub client: &'a Client,
}

impl<'a> RaftProxy<'a> {
    pub fn vote_async(
        &self,
        req: &VoteRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = req.clone();
        self.client.request_async(
            rpc_id::VOTE,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

    pub fn empty_append_entries_async(
        &self,
        req: &EmptyAppendEntriesRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = req.clone();
        self.client.request_async(
            rpc_id::EMPTYAPPENDENTRIES,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

    pub fn install_snapshot_async(
        &self,
        req: &InstallSnapshotRequest,
        on_reply: AsyncReplyCallback,
    ) -> Result<(), i32> {
        let payload = req.clone();
        self.client.request_async(
            rpc_id::INSTALLSNAPSHOT,
            move |ar: &mut BinaryWriteArchive| payload.serialize(ar),
            on_reply,
        )
    }

}

